import { CropReport, WeatherRisk, MarketPrice, Scheme } from '../types';

export const SEED_VILLAGES = [
  { id: 'v1', name: 'Thirthahalli (ತೀರ್ಥಹಳ್ಳಿ)', district: 'Shivamogga' },
  { id: 'v2', name: 'Ujire (ಉಜಿರೆ)', district: 'Dakshina Kannada' },
  { id: 'v3', name: 'Sullia (ಸುಳ್ಯ)', district: 'Dakshina Kannada' },
  { id: 'v4', name: 'Sirsi (ಶಿರಸಿ)', district: 'Uttara Kannada' },
];

export const SEED_REPORTS: CropReport[] = [
  {
    id: 'rep_101',
    crop: 'arecanut',
    cropNameKn: 'ಅಡಿಕೆ',
    cropNameEn: 'Arecanut',
    predictedDisease: 'Koleroga (Mahali)',
    predictedDiseaseKn: 'ಕೊಳೆ ರೋಗ (ಮಹಾಳಿ)',
    scientificName: 'Phytophthora meadii',
    confidence: 0.88,
    status: 'ai_analysed',
    villageId: 'v2',
    villageName: 'Ujire (ಉಜಿರೆ)',
    reporterRole: 'farmer',
    createdAt: '2026-09-24 10:30 AM',
    remedyKn: 'ಬೋರ್ಡೋ ಮಿಶ್ರಣ 1% (Bordeaux mixture 1%) ಸಿಂಪಡಿಸಿ. ಮಳೆ ಮುನ್ನ ತೋಟದಲ್ಲಿ ನೀರು ನಿಲ್ಲದಂತೆ ಬಸಿದು ಹೋಗಲು ಕಾಲುವೆ ಮಾಡಿ.',
    remedyEn: 'Spray 1% Bordeaux mixture before onset of heavy rain. Ensure proper drainage in the garden to avoid water stagnation.',
    sourceInstitution: 'ICAR-CPCRI Kasaragod',
    evidenceFarmsCount: 1,
  },
  {
    id: 'rep_102',
    crop: 'paddy',
    cropNameKn: 'ಭತ್ತ',
    cropNameEn: 'Paddy',
    predictedDisease: 'Blast Disease',
    predictedDiseaseKn: 'ಬ್ಲಾಸ್ಟ್ ರೋಗ',
    scientificName: 'Magnaporthe oryzae',
    confidence: 0.92,
    status: 'corroborated',
    villageId: 'v1',
    villageName: 'Thirthahalli (ತೀರ್ಥಹಳ್ಳಿ)',
    reporterRole: 'farmer',
    createdAt: '2026-09-23 04:15 PM',
    remedyKn: 'ಟ್ರೈಸೈಕ್ಲಜೋಲ್ 75 ಡಬ್ಲ್ಯೂಪಿ (Tricyclazole 75 WP) @ 0.6 ಗ್ರಾಂ/ಲೀಟರ್ ನೀರಿಗೆ ಬೆರೆಸಿ ಸಿಂಪಡಿಸಿ.',
    remedyEn: 'Spray Tricyclazole 75 WP @ 0.6g/liter of water at early tillering stage.',
    sourceInstitution: 'ICAR-DRR Hyderabad',
    evidenceFarmsCount: 3,
  },
  {
    id: 'rep_103',
    crop: 'arecanut',
    cropNameKn: 'ಅಡಿಕೆ',
    cropNameEn: 'Arecanut',
    predictedDisease: 'Bud Rot',
    predictedDiseaseKn: 'ಸುಳಿ ಕೊಳೆ ರೋಗ',
    scientificName: 'Phytophthora palmivora',
    confidence: 0.95,
    status: 'expert_verified',
    villageId: 'v2',
    villageName: 'Ujire (ಉಜಿರೆ)',
    reporterRole: 'village_node',
    proxyFor: 'ಮಂಜುನಾಥ ಗೌಡ',
    createdAt: '2026-09-22 09:00 AM',
    remedyKn: 'ಸೋಂಕಿತ ಸುಳಿಯನ್ನು ಕತ್ತರಿಸಿ ತೆಗೆದು ಬೋರ್ಡೋ ಪೇಸ್ಟ್ ಲೇಪಿಸಿ.',
    remedyEn: 'Remove and destroy infected spindle; apply Bordeaux paste to cut surface.',
    sourceInstitution: 'ICAR-CPCRI Kasaragod',
    evidenceFarmsCount: 4,
    verifiedBy: 'Agriculture Officer, Belthangady KVK',
    verifiedAt: '2026-09-23 11:30 AM',
  }
];

export const SEED_WEATHER_RISKS: Record<string, WeatherRisk> = {
  arecanut: {
    villageId: 'v2',
    villageName: 'Ujire',
    crop: 'Arecanut',
    riskLevel: 'HIGH',
    diseaseRisk: 'Koleroga (Fruit Rot)',
    diseaseRiskKn: 'ಕೊಳೆ ರೋಗ (ಮಹಾಳಿ) ಹೆಚ್ಚಿನ ಅಪಾಯ',
    triggerCondition: 'ತೇವಾಂಶ > 85% + ಸತತ ಮಳೆ (Sustained humidity >85%)',
    advisoryKn: 'ಮುಂದಿನ 48 ಗಂಟೆಗಳಲ್ಲಿ ಭಾರಿ ಮಳೆಯ ಸಂಭವವಿದೆ. ಅಡಿಕೆ ಗೊಂಚಲುಗಳಿಗೆ 1% ಬೋರ್ಡೋ ಮಿಶ್ರಣ ಸಿಂಪಡಣೆ ತಕ್ಷಣ ಪೂರ್ಣಗೊಳಿಸಿ.',
    advisoryEn: 'Heavy rain expected in next 48 hours. Complete 1% Bordeaux mixture preventive spray immediately.',
    humidity: 89,
    tempMin: 22,
    tempMax: 27,
    rainfallMm: 45,
    validUntil: '28 Sep 2026',
    source: 'ICAR-CPCRI Weather Advisory Rules',
  },
  paddy: {
    villageId: 'v1',
    villageName: 'Thirthahalli',
    crop: 'Paddy',
    riskLevel: 'MEDIUM',
    diseaseRisk: 'Paddy Blast Alert',
    diseaseRiskKn: 'ಭತ್ತದ ಬ್ಲಾಸ್ಟ್ ರೋಗದ ಎಚ್ಚರಿಕೆ',
    triggerCondition: 'ತಾಪಮಾನ 22-28°C + ತೇವಾಂಶ 80-90%',
    advisoryKn: 'ತೆನೆ ಬರುವ ಮುನ್ನ ಗದ್ದೆಯನ್ನು ಪರಿಶೀಲಿಸಿ. ಕಂದು ಚುಕ್ಕೆಗಳು ಕಂಡುಬಂದರೆ ಟ್ರೈಸೈಕ್ಲಜೋಲ್ ಔಷಧ ಸಿದ್ಧಪಡಿಸಿಕೊಳ್ಳಿ.',
    advisoryEn: 'Inspect fields before panicle emergence. Keep Tricyclazole spray ready if eye-shaped lesions appear.',
    humidity: 82,
    tempMin: 23,
    tempMax: 29,
    rainfallMm: 12,
    validUntil: '27 Sep 2026',
    source: 'ICAR-DRR Agricultural Meteorological Rules',
  }
};

export const SEED_MARKET_PRICES: MarketPrice[] = [
  {
    id: 'm1',
    crop: 'Arecanut (Chali / ಚಾಲಿ)',
    cropKn: 'ಅಡಿಕೆ (ಚಾಲಿ)',
    sourceLabel: 'APMC Shimoga (ಮಂಡಿ)',
    sourceType: 'APMC',
    pricePerQuintal: 48500,
    recordedAt: 'ಇಂದು, 10:30 AM',
  },
  {
    id: 'm2',
    crop: 'Arecanut (Chali / ಚಾಲಿ)',
    cropKn: 'ಅಡಿಕೆ (ಚಾಲಿ)',
    sourceLabel: 'TMC Traders, Ujire (ಸ್ಥಳೀಯ ಖರೀದಿ)',
    sourceType: 'Buyer',
    pricePerQuintal: 49200,
    recordedAt: 'ಇಂದು, 09:15 AM',
  },
  {
    id: 'm3',
    crop: 'Arecanut (Chali / ಚಾಲಿ)',
    cropKn: 'ಅಡಿಕೆ (ಚಾಲಿ)',
    sourceLabel: 'ರೈತರು ವರದಿ ಮಾಡಿದ ದರ (Farmer Reported)',
    sourceType: 'Farmer Reported',
    pricePerQuintal: 48800,
    recordedAt: 'ನಿನ್ನೆ, 05:00 PM',
  },
  {
    id: 'm4',
    crop: 'Paddy (Sona Masoori / ಸೋನಾ ಮಸೂರಿ)',
    cropKn: 'ಭತ್ತ (ಸೋನಾ ಮಸೂರಿ)',
    sourceLabel: 'APMC Belthangady',
    sourceType: 'APMC',
    pricePerQuintal: 2450,
    recordedAt: 'ಇಂದು, 11:00 AM',
  }
];

export const SEED_SCHEMES: Scheme[] = [
  {
    id: 'sch1',
    nameKn: 'ತೋಟಗಾರಿಕೆ ಕೀಟನಾಶಕ ಸಹಾಯಧನ ಯೋಜನೆ',
    nameEn: 'Horticultural Disease Control & Spray Subsidy',
    department: 'ಕರ್ನಾಟಕ ತೋಟಗಾರಿಕೆ ಇಲಾಖೆ (Dept of Horticulture)',
    crop: 'Arecanut (ಅಡಿಕೆ)',
    district: 'Dakshina Kannada / Shivamogga / Udupi',
    eligibilityKn: 'ಮಲೆನಾಡು & ಕರಾವಳಿ ಭಾಗದ ಸಣ್ಣ ಮತ್ತು ಅತಿ ಸಣ್ಣ ಅಡಿಕೆ ಬೆಳೆಗಾರರಿಗೆ',
    eligibilityEn: 'Small and marginal arecanut growers in Malnad & Coastal Karnataka',
    benefitKn: 'ಬೋರ್ಡೋ ಮಿಶ್ರಣ ಮತ್ತು ಸಿಂಪಡಣೆ ಉಪಕರಣಗಳಿಗೆ 50% ಸಹಾಯಧನ',
    benefitEn: '50% subsidy on Bordeaux mixture chemicals and power sprayers',
    officialSourceUrl: 'https://horticulturedir.karnataka.gov.in',
    lastVerified: 'Sep 2026',
  },
  {
    id: 'sch2',
    nameKn: 'ಪ್ರಧಾನ ಮಂತ್ರಿ ಫಸಲ್ ಬಿಮಾ ಯೋಜನೆ (PMFBY)',
    nameEn: 'Pradhan Mantri Fasal Bima Yojana (Crop Insurance)',
    department: 'ಕೃಷಿ ಸಚಿವಾಲಯ (Ministry of Agriculture)',
    crop: 'Paddy & Arecanut (ಭತ್ತ ಮತ್ತು ಅಡಿಕೆ)',
    district: 'All Karnataka Districts',
    eligibilityKn: 'ನೈಸರ್ಗಿಕ ವಿಕೋಪ ಮತ್ತು ರೋಗ ಬಾಧೆಯಿಂದ ಬೆಳೆ ನಷ್ಟ ಅನುಭವಿಸಿದ ಎಲ್ಲ ರೈತರಿಗೆ',
    eligibilityEn: 'All farmers suffering yield loss due to non-preventable natural risks',
    benefitKn: 'ಕನಿಷ್ಠ ಪ್ರೀಮಿಯಂನಲ್ಲಿ ಸಮಗ್ರ ಬೆಳೆ ವಿಮೆ ರಕ್ಷಣೆ',
    benefitEn: 'Comprehensive financial support for crop loss at minimal premium',
    officialSourceUrl: 'https://pmfby.gov.in',
    lastVerified: 'Sep 2026',
  }
];
