import { CropReport, WeatherRisk, MarketPrice, Scheme } from '../types';

export const SEED_VILLAGES = [
  { id: 'v1', name: 'ತೀರ್ಥಹಳ್ಳಿ (Thirthahalli)', district: 'Shivamogga' },
  { id: 'v2', name: 'ಉಜಿರೆ (Ujire)', district: 'Dakshina Kannada' },
  { id: 'v3', name: 'ಸುಳ್ಯ (Sullia)', district: 'Dakshina Kannada' },
  { id: 'v4', name: 'ಶಿರಸಿ (Sirsi)', district: 'Uttara Kannada' },
];

export const SEED_REPORTS: CropReport[] = [
  {
    id: 'rep_101',
    crop: 'arecanut',
    cropNameKn: 'ಅಡಿಕೆ',
    cropNameEn: 'Arecanut',
    predictedDisease: 'Koleroga (Mahali)',
    predictedDiseaseKn: 'ಕೊಳೆರೋಗ (ಮಹಾಲಿ)',
    scientificName: 'Phytophthora meadii',
    confidence: 0.88,
    status: 'ai_analysed',
    villageId: 'v2',
    villageName: 'ಉಜಿರೆ (Ujire)',
    reporterRole: 'farmer',
    createdAt: '2026-09-24 10:30 AM',
    remedyKn: 'ಬೋರ್ಡೋ ದ್ರಾವಣ 1% (Bordeaux mixture 1%) ಸಿಂಪಡಿಸಿ. ತೋಟದಲ್ಲಿ ನೀರು ನಿಲ್ಲದಂತೆ ಬಸಿಗಾಲುವೆ ಸರಿಪಡಿಸಿ.',
    remedyEn: 'Spray 1% Bordeaux mixture before onset of heavy rain. Ensure proper drainage in the garden to avoid water stagnation.',
    sourceInstitution: 'ICAR-CPCRI Kasaragod',
    evidenceFarmsCount: 1,
  },
  {
    id: 'rep_102',
    crop: 'paddy',
    cropNameKn: 'ಭತ್ತ',
    cropNameEn: 'Paddy',
    predictedDisease: 'Blast Disease',
    predictedDiseaseKn: 'ಬೆಂಕಿ ರೋಗ (ಬ್ಲಾಸ್ಟ್)',
    scientificName: 'Magnaporthe oryzae',
    confidence: 0.94,
    status: 'corroborated',
    villageId: 'v1',
    villageName: 'ತೀರ್ಥಹಳ್ಳಿ (Thirthahalli)',
    reporterRole: 'farmer',
    createdAt: '2026-09-24 08:15 AM',
    remedyKn: 'ಟ್ರೈಸೈಕ್ಲಾಜೋಲ್ 75 ಡಬ್ಲ್ಯೂಪಿ @ 0.6 ಗ್ರಾಂ/ಲೀಟರ್ ನೀರಿಗೆ ಬೆರೆಸಿ ಸಿಂಪಡಿಸಿ.',
    remedyEn: 'Spray Tricyclazole 75% WP @ 0.6g per litre of water. Avoid excess urea application.',
    sourceInstitution: 'ICAR-IIRR Hyderabad',
    evidenceFarmsCount: 3,
  },
  {
    id: 'rep_103',
    crop: 'coconut',
    cropNameKn: 'ತೆಂಗು',
    cropNameEn: 'Coconut',
    predictedDisease: 'Bud Rot',
    predictedDiseaseKn: 'ಸುಳಿ ಕೊಳೆ ರೋಗ',
    scientificName: 'Phytophthora palmivora',
    confidence: 0.91,
    status: 'expert_verified',
    villageId: 'v3',
    villageName: 'ಸುಳ್ಯ (Sullia)',
    reporterRole: 'expert',
    createdAt: '2026-09-23 04:45 PM',
    remedyKn: 'ಬಾಧಿತ ಸುಳಿಯನ್ನು ಕತ್ತರಿಸಿ ತೆಗೆದು ಬೋರ್ಡೋ ಪೇಸ್ಟ್ ಲೇಪಿಸಿ. 1% ಬೋರ್ಡೋ ದ್ರಾವಣ ಸಿಂಪಡಿಸಿ.',
    remedyEn: 'Cut infected tissues and apply Bordeaux paste on the crown. Spray 1% Bordeaux mixture.',
    sourceInstitution: 'KVK Dakshina Kannada',
    evidenceFarmsCount: 4,
    verifiedBy: 'Dr. Ramesh K, KVK Brahmavar',
    verifiedAt: '2026-09-23 05:30 PM',
  },
];

export const SEED_WEATHER_RISKS: WeatherRisk[] = [
  {
    villageId: 'v2',
    villageName: 'ಉಜಿರೆ (Ujire)',
    crop: 'ಅಡಿಕೆ (Arecanut)',
    riskLevel: 'HIGH',
    diseaseRisk: 'Koleroga (Fruit Rot)',
    diseaseRiskKn: 'ಕೊಳೆರೋಗ ತೀವ್ರ ಅಪಾಯ',
    triggerCondition: '3 ದಿನಗಳಿಂದ ಎಡೆಬಿಡದೆ ಮಳೆ + 92% ತೇವಾಂಶ (3 days continuous rain + 92% RH)',
    advisoryKn: 'ಕೂಡಲೇ ಬೋರ್ಡೋ ದ್ರಾವಣ 1% ಸಿಂಪಡಿಸಿ. ಕಾಯಿಗಳಿಗೆ ಕವರ್ ಕಟ್ಟಿ.',
    advisoryEn: 'Apply 1% Bordeaux mixture with stickers. Tie aerated polythene covers.',
    humidity: 92,
    tempMin: 22,
    tempMax: 27,
    rainfallMm: 68.5,
    validUntil: '2026-09-27',
    source: 'IMD + UAS Bangalore Agromet',
  },
  {
    villageId: 'v1',
    villageName: 'ತೀರ್ಥಹಳ್ಳಿ (Thirthahalli)',
    crop: 'ಭತ್ತ (Paddy)',
    riskLevel: 'MEDIUM',
    diseaseRisk: 'Blast (Magnaporthe)',
    diseaseRiskKn: 'ಬೆಂಕಿ ರೋಗ ಮಧ್ಯಮ ಅಪಾಯ',
    triggerCondition: 'ಮಂಜು ಕವಿದ ವಾತಾವರಣ + ರಾತ್ರಿ ಕಡಿಮೆ ತಾಪಮಾನ 20°C',
    advisoryKn: 'ಯೂರಿಯಾ ಗೊಬ್ಬರ ಅತಿಯಾಗಿ ಬಳಸಬೇಡಿ. ಟ್ರೈಸೈಕ್ಲಾಜೋಲ್ ಸಿಂಪಡಣೆಗೆ ಸಿದ್ಧತೆ ಮಾಡಿಕೊಳ್ಳಿ.',
    advisoryEn: 'Avoid excessive nitrogen. Keep Tricyclazole spray ready.',
    humidity: 84,
    tempMin: 20,
    tempMax: 29,
    rainfallMm: 24.0,
    validUntil: '2026-09-26',
    source: 'IMD Coastal Agromet',
  },
];

export const SEED_MARKET_PRICES: MarketPrice[] = [
  {
    id: 'm1',
    crop: 'Arecanut (Chali / ಚಾಲಿ)',
    cropKn: 'ಅಡಿಕೆ (ಚಾಲಿ)',
    sourceLabel: 'APMC Shimoga (ಶಿವಮೊಗ್ಗ)',
    sourceType: 'APMC',
    pricePerQuintal: 48500,
    recordedAt: 'ಇಂದು, 10:30 AM',
  },
  {
    id: 'm2',
    crop: 'Arecanut (Chali / ಚಾಲಿ)',
    cropKn: 'ಅಡಿಕೆ (ಚಾಲಿ)',
    sourceLabel: 'TMC Traders, Ujire (ಖಾಸಗಿ ವರ್ತಕರು)',
    sourceType: 'Buyer',
    pricePerQuintal: 49200,
    recordedAt: 'ಇಂದು, 09:15 AM',
  },
  {
    id: 'm3',
    crop: 'Arecanut (Chali / ಚಾಲಿ)',
    cropKn: 'ಅಡಿಕೆ (ಚಾಲಿ)',
    sourceLabel: 'ಸ್ಥಳೀಯ ಬೆಳೆಗಾರರ ಮಾರಾಟ (Farmer Reported)',
    sourceType: 'Farmer Reported',
    pricePerQuintal: 48800,
    recordedAt: 'ನಿನ್ನೆ, 05:00 PM',
  },
  {
    id: 'm4',
    crop: 'Paddy (Sona Masoori / ಸೋನಾ ಮಸೂರಿ)',
    cropKn: 'ಭತ್ತ (ಸೋನಾ ಮಸೂರಿ)',
    sourceLabel: 'APMC Davanagere',
    sourceType: 'APMC',
    pricePerQuintal: 2450,
    recordedAt: 'ಇಂದು, 11:00 AM',
  },
  {
    id: 'm5',
    crop: 'Black Pepper (ಕಾಳುಮೆಣಸು)',
    cropKn: 'ಕಾಳುಮೆಣಸು (Black Pepper)',
    sourceLabel: 'Sirsi APMC (ಶಿರಸಿ)',
    sourceType: 'APMC',
    pricePerQuintal: 62000,
    recordedAt: 'ಇಂದು, 10:45 AM',
  },
];

export const SEED_SCHEMES: Scheme[] = [
  {
    id: 'sch1',
    nameKn: 'ತೋಟಗಾರಿಕಾ ರೋಗ ನಿಯಂತ್ರಣ ಹಾಗೂ ಸಿಂಪರಣಾ ಸಬ್ಸಿಡಿ',
    nameEn: 'Horticultural Disease Control & Spray Subsidy',
    department: 'ತೋಟಗಾರಿಕೆ ಇಲಾಖೆ (Dept of Horticulture)',
    crop: 'Arecanut (ಅಡಿಕೆ)',
    district: 'Dakshina Kannada / Shivamogga / Udupi',
    eligibilityKn: 'ಸಣ್ಣ ಮತ್ತು ಅತಿ ಸಣ್ಣ ಅಡಿಕೆ ಬೆಳೆಗಾರರು',
    eligibilityEn: 'Small and marginal arecanut growers in Malnad & Coastal Karnataka',
    benefitKn: 'ಬೋರ್ಡೋ ಔಷಧಿ ಹಾಗೂ ಪವರ್ ಸ್ಪ್ರೇಯರ್‌ಗೆ 50% ಸಬ್ಸಿಡಿ',
    benefitEn: '50% subsidy on Bordeaux mixture chemicals and power sprayers',
    officialSourceUrl: 'https://horticulturedir.karnataka.gov.in',
    lastVerified: 'Sep 2026',
  },
  {
    id: 'sch2',
    nameKn: 'ಪ್ರಧಾನ ಮಂತ್ರಿ ಫಸಲ್ ಬಿಮಾ ಯೋಜನೆ (PMFBY)',
    nameEn: 'Pradhan Mantri Fasal Bima Yojana (Crop Insurance)',
    department: 'ಕೃಷಿ ಸಚಿವಾಲಯ (Ministry of Agriculture)',
    crop: 'Paddy & Arecanut (ಭತ್ತ ಮತ್ತು ಅಡಿಕೆ)',
    district: 'All Karnataka Districts',
    eligibilityKn: 'ನೈಸರ್ಗಿಕ ವಿಕೋಪ ಮತ್ತು ರೋಗಬಾಧೆಯಿಂದ ಬೆಳೆ ಹಾನಿಗೊಳಗಾದ ಎಲ್ಲಾ ರೈತರು',
    eligibilityEn: 'All farmers suffering yield loss due to non-preventable natural risks',
    benefitKn: 'ಕಡಿಮೆ ಪ್ರೀಮಿಯಂನಲ್ಲಿ ಸಂಪೂರ್ಣ ಬೆಳೆ ವಿಮೆ ಪರಿಹಾರ',
    benefitEn: 'Comprehensive financial support for crop loss at minimal premium',
    officialSourceUrl: 'https://pmfby.gov.in',
    lastVerified: 'Sep 2026',
  },
];
