"""Pydantic data schemas for KrushiPragya API."""
from app.schemas.health import HealthResponse
from app.schemas.weather import (
    WeatherData,
    ForecastData,
    WeatherObserveRequest,
    WeatherObservationResponse,
    WeatherMetricsResponse,
    AdvisoryMatchResponse,
    WeatherAdvisoriesResponse,
    WeatherForecastResponse,
    ForecastMetrics,
    UnsupportedRuleResponse,
    ForecastAdvisoryResponse,
    ForecastAdvisoryContext,
    FarmerAdvisoryItem,
    FarmerAdvisoryResponse,
    AdvisoryProvenance,
    AdvisoryExplanation,
)
from app.schemas.disease import (
    ClassPrediction,
    DiseasePredictionResponse,
)
from app.schemas.farmer import (
    FarmerProfileCreate,
    FarmerProfileUpdate,
    FarmerProfileResponse,
)
from app.schemas.farmer_crop import (
    CropResponse,
    FarmerCropCreate,
    FarmerCropUpdate,
    FarmerCropResponse,
    FarmerCropWithDetailsResponse,
)
from app.schemas.crop_report import (
    CropReportCreate,
    CropReportUpdate,
    CropReportResponse,
    CropReportWithCropResponse,
    CropReportImageResponse,
    DiseasePredictionResult,
    CropReportDiagnosisResponse,
    CropReportDiagnosisRecordResponse,
)

__all__ = [
    "HealthResponse",
    "WeatherData",
    "ForecastData",
    "WeatherObserveRequest",
    "WeatherObservationResponse",
    "WeatherMetricsResponse",
    "AdvisoryMatchResponse",
    "WeatherAdvisoriesResponse",
    "WeatherForecastResponse",
    "ForecastMetrics",
    "UnsupportedRuleResponse",
    "ForecastAdvisoryResponse",
    "ForecastAdvisoryContext",
    "FarmerAdvisoryItem",
    "FarmerAdvisoryResponse",
    "AdvisoryProvenance",
    "AdvisoryExplanation",
    "ClassPrediction",
    "DiseasePredictionResponse",
    "FarmerProfileCreate",
    "FarmerProfileUpdate",
    "FarmerProfileResponse",
    "CropResponse",
    "FarmerCropCreate",
    "FarmerCropUpdate",
    "FarmerCropResponse",
    "FarmerCropWithDetailsResponse",
    "CropReportCreate",
    "CropReportUpdate",
    "CropReportResponse",
    "CropReportWithCropResponse",
    "CropReportImageResponse",
    "DiseasePredictionResult",
    "CropReportDiagnosisResponse",
    "CropReportDiagnosisRecordResponse",
]
