"""create_crop_reports_table

Revision ID: a749dc1e3ab3
Revises: df72befe0543
Create Date: 2026-09-24 21:39:50.724707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a749dc1e3ab3'
down_revision: Union[str, Sequence[str], None] = 'df72befe0543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('farmer_crop_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('image_storage_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_crop_id'], ['farmer_crops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_reports_farmer_crop_id'), 'crop_reports', ['farmer_crop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_reports_farmer_crop_id'), table_name='crop_reports')
    op.drop_table('crop_reports')
    # ### end Alembic commands ###
