"""create_weather_observations_table

Revision ID: df72befe0543
Revises: 1c41e2dc0718
Create Date: 2026-09-23 22:50:38.960345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df72befe0543'
down_revision: Union[str, Sequence[str], None] = '1c41e2dc0718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_observations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('village_id', sa.String(length=50), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rainfall_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('wind_speed_kmh', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('wind_direction_deg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pressure_hpa', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('cloud_cover_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weather_condition', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cloud_cover_pct >= 0 AND cloud_cover_pct <= 100', name='ck_weather_observations_cloud_cover_pct'),
    sa.CheckConstraint('humidity_pct >= 0 AND humidity_pct <= 100', name='ck_weather_observations_humidity_pct'),
    sa.CheckConstraint('pressure_hpa > 0', name='ck_weather_observations_pressure_hpa'),
    sa.CheckConstraint('rainfall_mm >= 0', name='ck_weather_observations_rainfall_mm'),
    sa.CheckConstraint('wind_direction_deg >= 0 AND wind_direction_deg <= 360', name='ck_weather_observations_wind_direction_deg'),
    sa.CheckConstraint('wind_speed_kmh >= 0', name='ck_weather_observations_wind_speed_kmh'),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_observations_observed_at'), 'weather_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_weather_observations_village_id'), 'weather_observations', ['village_id'], unique=False)
    op.create_index('ix_weather_observations_village_id_observed_at', 'weather_observations', ['village_id', 'observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_observations_village_id_observed_at', table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_village_id'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_observed_at'), table_name='weather_observations')
    op.drop_table('weather_observations')
    # ### end Alembic commands ###
